---
abstract: 'simple access to Linux /proc/../statm'
author:
  - 'Robert Rothenberg <rrwo@thermeon.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Linux-Statm-Tiny
requires:
  Fcntl: '0'
  Moo: '0'
  Types::Standard: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/robrwo/Linux-Statm-Tiny/issues
  repository: git://github.com/robrwo/Linux-Statm-Tiny.git
version: '0.0201'
